services:
  - type: web
    name: skillbridge-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://frontend-qat4le47y-vishnus-projects-74225a00.vercel.app

databases:
  - name: skillbridge-db
    databaseName: skillbridge
    user: skillbridge
